[package]
name = "pallet-hybrid-vm-port"
version = "0.4.0"
license = "Apache-2.0"
description = "HybridVM port pallet for HybridVM."
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ethereum = { workspace = true, features = ["with-codec"] }
ethereum-types = { workspace = true }
evm = { workspace = true, features = ["with-codec"] }
scale-codec = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }
# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
pallet-contracts = { workspace = true, default-features = false }
# Frontier
fp-consensus = { workspace = true }
fp-ethereum = { workspace = true }
fp-evm = { workspace = true }
fp-rpc = { workspace = true }
fp-storage = { workspace = true }
pallet-evm = { workspace = true }
precompile-utils = { workspace = true }

#local
pallet-hybrid-vm =  { workspace = true, default-features = false }
hp-system =  { workspace = true, default-features = false }

[dev-dependencies]
byte-slice-cast= { workspace = true }
hex = { workspace = true }
libsecp256k1 = { workspace = true, features = ["static-context", "hmac"] }
rlp = { workspace = true }
sha3 = { workspace = true }
# Substrate
pallet-balances = { workspace = true, features = ["default", "insecure_zero_ed"] }
pallet-insecure-randomness-collective-flip = { workspace = true, default-features = false}
pallet-timestamp = { workspace = true, features = ["default"] }
sp-core = { workspace = true, features = ["default"] }
sp-std = { workspace = true, features = ["default"] }
# Frontier
fp-self-contained = { workspace = true, features = ["default"] }
# ink!
ink_env = { workspace = true, features = ["no-panic-handler"] }

[features]
default = ["std"]
std = [
	"ethereum/std",
	"evm/std",
	"ethereum-types/std",
	"rlp/std",
	"scale-codec/std",
	"scale-info/std",
	"ink_env/std",
	# Substrate
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-runtime/std",
	# Frontier
	"fp-consensus/std",
	"fp-ethereum/std",
	"fp-evm/std",
	"fp-rpc/std",
	"fp-storage/std",
	"pallet-evm/std",
	"pallet-contracts/std",
	"precompile-utils/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-evm/try-runtime",
	"pallet-contracts/try-runtime",
]
forbid-evm-reentrancy = ["pallet-evm/forbid-evm-reentrancy"]
